global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Cardano Node Metrics
  - job_name: 'cardano-node'
    static_configs:
      - targets: ['cardano-node:12798']
        labels:
          instance: 'cardano-node-main'
          network: 'testnet'  # Change to 'mainnet' for production

  # API Server Metrics
  - job_name: 'api-server'
    static_configs:
      - targets: ['api-server:9090']
        labels:
          instance: 'api-server-main'

  # Frontend Metrics
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend-metrics:9091']
        labels:
          instance: 'frontend-main'

  # Database Metrics
  - job_name: 'database'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          instance: 'postgres-main'

  # IPFS Metrics
  - job_name: 'ipfs'
    static_configs:
      - targets: ['ipfs-node:5001']
        labels:
          instance: 'ipfs-main'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'node-main'

  # Blockchain Transaction Metrics
  - job_name: 'blockchain-metrics'
    static_configs:
      - targets: ['blockchain-metrics:9092']
        labels:
          instance: 'blockchain-metrics-main'
